name: Feature Request
description: File a report to suggest an idea for this project
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request report!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a brief description of your feature request.
    validations:
      required: true
  - type: textarea
    id: drawbacks
    attributes:
      label: Drawbacks
      description: Identify the drawbacks and impacts while being neutral on your feature request.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Solution
      description: |
        Provide a description of your preferred solution.

        This can include:
        * Details of the technical implementation
        * Tradeoffs made in design decisions
        * Caveats and considerations for the future
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct.
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
